version: "3.4"

services:
  scylladb:
    image: scylladb/scylla:4.1.0
    command: --smp 1 --memory 1G
    ports:
      - 13253:9042
    volumes:
      - /home/zest/twake/docker-data/scylladb:/var/lib/scylla

  rabbitmq:
    image: rabbitmq:3

  node:
    image: twaketech/twake-node:2021.Q2.505
    environment:
      - NODE_ENV=production
      - PUBSUB_URLS=amqp://guest:guest@rabbitmq:5672
    volumes:
      - /home/zest/twake/configuration/backend-node/production.json:/usr/src/app/config/production.json
      - /home/zest/twake/docker-data/documents/:/storage/
    depends_on:
      - scylladb
      - rabbitmq
    links:
      - scylladb

  php:
    image: twaketech/twake-php:2021.Q2.505
    environment:
      - DEV=production
    volumes:
      - /home/zest/twake/configuration/backend/Parameters.php:/configuration/Parameters.php
      - /home/zest/twake/connectors/:/twake-core/src/BuiltInConnectors/Connectors
      - /home/zest/twake/docker-data/drive/:/twake-core/drive/
      - /home/zest/twake/docker-data/fpm/:/etc/docker-data/fpm/
      - /home/zest/twake/docker-data/drive-preview/:/twake-core/web/medias/
      - /home/zest/twake/docker-data/uploads/:/twake-core/web/upload/
    depends_on:
      - scylladb
      - rabbitmq
    links:
      - scylladb

  nginx:
    image: twaketech/twake-nginx:2021.Q2.505
    environment:
      - DEV=production
      - SSL_CERTS=selfsigned
    ports:
      - 13252:80
      - 13251:443
    depends_on:
      - php
      - node
    volumes:
      - /home/zest/twake/docker-data/logs/nginx/:/var/log/nginx
      - /home/zest/twake/docker-data/letsencrypt/:/etc/letsencrypt/
      - /home/zest/twake/docker-data/drive-preview/:/twake-core/web/medias/
      - /home/zest/twake/docker-data/uploads/:/twake-core/web/upload/
      - /home/zest/twake/docker-data/ssl:/etc/nginx/ssl
