version: "3.4"

services:
  mongo:
    image: mongo
    volumes:
      - /home/zest/zesthq/docker-data/mongo:/data/db

  node:
    image: twaketech/twake-node:latest
    ports:
      - 13251:3000
      - 13252:3000
    environment:
      - DEV=production
      - SEARCH_DRIVER=mongodb
      - DB_DRIVER=mongodb
      - PUBSUB_TYPE=local
    volumes:
      - /home/zest/zesthq/configuration/backend-node/production.json:/usr/src/app/config/production.json
      - /home/zest/zesthq/docker-data/documents/:/storage/
    depends_on:
      - mongo
    links:
      - mongo
